server:
  port: 80

springdoc:
  swagger-ui:
    path: /doc/api
  api-docs:
    path: /doc/api-docs
  version: 1.6.8

spring:
  application:
    name: spring-boot-auth
  main:
    allow-circular-references: true
#  sql:
#    init:
#      mode: never #ALWAYS, EMBEDDED, NEVER; change to always to auto generation data.sql
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://35.232.15.111:3306/mySchema?noAccessToProcedureBodies=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 217478423053-vp8klmp6ks0n6ucidcnro7vjb9vge674.apps.googleusercontent.com
            client-secret: Pm0Vcb6b0Eh96Gp9-Nij81E1
#            redirect-uri: http://localhost:8081/
          facebook:
            client-id: 190018635382272
            client-secret: 9697669ed162d59126ea6948942f34b4
  mail:
    port: 587
    host: smtp.gmail.com
    username: noreply.trungtq@gmail.com
    password: /PMHYs[3k2:j@gQX6rUE3zD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

vnpay:
  terminalId: 12186H5A
  secretKey: FMVUVYBYKIMOYLLMPJBBJVKEEKHWXPCS