package site.code4fun.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
public class ErrorDTO {
	private Type type; // toast type at client
	private String title;
	private Integer code;
	private String detail;
	private String instance;

	public enum Type{
		basic, primary, success, warning, danger, info, control
	}

//	o  "title" (string) - A short, human-readable summary of the problem
//	type.  It SHOULD NOT change from occurrence to occurrence of the
//	problem, except for purposes of localization (e.g., using
//			proactive content negotiation; see [RFC7231], Section 3.4).
//
//	o  "status" (number) - The HTTP status code ([RFC7231], Section 6)
//	generated by the origin server for this occurrence of the problem.
//
//	o  "detail" (string) - A human-readable explanation specific to this
//	occurrence of the problem.
//
//	o  "instance" (string) - A URI reference that identifies the specific
//	occurrence of the problem.  It may or may not yield further
//	information if dereferenced.
}
