runtime: java11
instance_class: F4_1G
service: default
handlers:
  - url: /(.*)
    script: auto
    secure: always
automatic_scaling:
  min_instances: 1
  max_instances: 1
#entrypoint: java -Dthin.root=. -jar my-app-0.0.1-SNAPSHOT.jar
